# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: yEZIno9QN3Ie4EOw37spRxJvAJZ9yL0j
    salt: "V36pDOhfaz9MABCdEnf5X7zOy2W8ydBC"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  digitalnomad.press:
    env:
      db_password: ZN8Gp1FhcVInW09DI2K56lc71uZn1xy6
      # Generate your keys here: https://roots.io/salts.html
      auth_key: ";@r,<RMxR16rLQR$;yNX/-E*V//C*fPWG$VYAAD#qlUobpzm2vo^SnjA?5,Y4iiB"
      secure_auth_key: "K2=ppD:f(u=,]<lfB}fyU1U5$so5%9W!owPKi>rG0IgDCjHOeQ7EqD9A?uo{!h/P"
      logged_in_key: "RpRW[C88{*V8:J|Fn9}NFm43kQ+XF3s|2EfnDzCd`4mp2<(Pag?{2M%On)wI)3*:"
      nonce_key: "U-i][beQ.3G-;:`HN#1kdrVcUHs||Og;8.#O[z&^=L4y;d&DS<>2!Nd1vb}!_U]^"
      auth_salt: "PWe]z=eGL/&z>z?_t4$,e|7AnU-*Y1}pF=>i$z92Ajzh6FrFy/r;]M6,]=hgd_$]"
      secure_auth_salt: "ZiSFx<jM|iW%gfCj5/l1M4#)Myt;WnKNkZ!fG,X`vp<nY9f-G&)HMp_cg).IvaRs"
      logged_in_salt: "xd#YY5c]v?a]y;>.lMEl/.$Qyc23Q*?glcF@0>_0gu|72OBAf<*r)E^ZA^>!b$Ig"
      nonce_salt: "yKVUwKs}pOT8bB-AR,G2z*Rso=%4@v[5t?bqqHWIVDFdjH-?hn3UoYv(Ve_Y=/XZ"